/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_chenzhuo_jni_test_utils_JniUtils */

#ifndef _Included_test_chenzhuo_jni_test_utils_JniUtils
#define _Included_test_chenzhuo_jni_test_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_chenzhuo_jni_test_utils_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_chenzhuo_jni_1test_utils_JniUtils_getJniString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
